PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 客户模块
    url(r'^Ziliao/', include('apps.Ziliao.urls', namespace='Ziliao')),  # 客户资料模块
    url(r'^Employee/', include('apps.Employee.urls', namespace='Employee')),  # 员工模块
    url(r'^LoanApply/', include('apps.LoanApply.urls', namespace='LoanApply')),  # 贷款申请模块
    url(r'^Payback/', include('apps.Payback.urls', namespace='Payback')),  # 还款记录模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Employee/urls.py
from apps.Employee.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, BackSelfModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Employee'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<employeeNo>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<employeeNo>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<employeeNo>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<employeeNo>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^backSelfModify$', BackSelfModifyView.as_view(), name="backSelfModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,MainEmployeeView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^main_employee$', MainEmployeeView.as_view(), name='main_employee'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Employee/models.py
from django.db import models


class Employee(models.Model):
    employeeNo = models.CharField(max_length=30, default='', primary_key=True, verbose_name='员工编号')
    password = models.CharField(max_length=30, default='', verbose_name='登录密码')
    name = models.CharField(max_length=20, default='', verbose_name='员工姓名')
    gender = models.CharField(max_length=4, default='', verbose_name='性别')
    inDate = models.CharField(max_length=20, default='', verbose_name='入职日期')
    empPhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='员工照片')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    email = models.CharField(max_length=50, default='', verbose_name='邮箱')
    address = models.CharField(max_length=80, default='', verbose_name='家庭地址')

    class Meta:
        db_table = 't_Employee'
        verbose_name = '员工信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        employee = {
            'employeeNo': self.employeeNo,
            'password': self.password,
            'name': self.name,
            'gender': self.gender,
            'inDate': self.inDate,
            'empPhoto': self.empPhoto.url,
            'telephone': self.telephone,
            'email': self.email,
            'address': self.address,
        }
        return employee


PythonProject/apps/Employee/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Employee.models import Employee
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台员工添加
    def primaryKeyExist(self, employeeNo):  # 判断主键是否存在
        try:
            Employee.objects.get(employeeNo=employeeNo)
            return True
        except Employee.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'Employee/employee_frontAdd.html')

    def post(self, request):
        employeeNo = request.POST.get('employee.employeeNo') # 判断员工编号是否存在
        if self.primaryKeyExist(employeeNo):
            return JsonResponse({'success': False, 'message': '员工编号已经存在'})

        employee = Employee() # 新建一个员工对象然后获取参数
        employee.employeeNo = employeeNo
        employee.password = request.POST.get('employee.password')
        employee.name = request.POST.get('employee.name')
        employee.gender = request.POST.get('employee.gender')
        employee.inDate = request.POST.get('employee.inDate')
        try:
            employee.empPhoto = self.uploadImageFile(request,'employee.empPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        employee.telephone = request.POST.get('employee.telephone')
        employee.email = request.POST.get('employee.email')
        employee.address = request.POST.get('employee.address')
        employee.save() # 保存员工信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改员工
    def get(self, request, employeeNo):
        context = {'employeeNo': employeeNo}
        return render(request, 'Employee/employee_frontModify.html', context)


class FrontListView(BaseView):  # 前台员工查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        employeeNo = self.getStrParam(request, 'employeeNo')
        name = self.getStrParam(request, 'name')
        inDate = self.getStrParam(request, 'inDate')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        employees = Employee.objects.all()
        if employeeNo != '':
            employees = employees.filter(employeeNo__contains=employeeNo)
        if name != '':
            employees = employees.filter(name__contains=name)
        if inDate != '':
            employees = employees.filter(inDate__contains=inDate)
        if telephone != '':
            employees = employees.filter(telephone__contains=telephone)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(employees, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        employees_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'employees_page': employees_page,
            'employeeNo': employeeNo,
            'name': name,
            'inDate': inDate,
            'telephone': telephone,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Employee/employee_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示员工详情页
    def get(self, request, employeeNo):
        # 查询需要显示的员工对象
        employee = Employee.objects.get(employeeNo=employeeNo)
        context = {
            'employee': employee
        }
        # 渲染模板显示
        return render(request, 'Employee/employee_frontshow.html', context)


class ListAllView(View): # 前台查询所有员工
    def get(self,request):
        employees = Employee.objects.all()
        employeeList = []
        for employee in employees:
            employeeObj = {
                'employeeNo': employee.employeeNo,
                'name': employee.name,
            }
            employeeList.append(employeeObj)
        return JsonResponse(employeeList, safe=False)


class UpdateView(BaseView):  # Ajax方式员工更新
    def get(self, request, employeeNo):
        # GET方式请求查询员工对象并返回员工json格式
        employee = Employee.objects.get(employeeNo=employeeNo)
        return JsonResponse(employee.getJsonObj())

    def post(self, request, employeeNo):
        # POST方式提交员工修改信息更新到数据库
        employee = Employee.objects.get(employeeNo=employeeNo)
        employee.password = request.POST.get('employee.password')
        employee.name = request.POST.get('employee.name')
        employee.gender = request.POST.get('employee.gender')
        employee.inDate = request.POST.get('employee.inDate')
        try:
            empPhotoName = self.uploadImageFile(request, 'employee.empPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if empPhotoName != 'img/NoImage.jpg':
            employee.empPhoto = empPhotoName
        employee.telephone = request.POST.get('employee.telephone')
        employee.email = request.POST.get('employee.email')
        employee.address = request.POST.get('employee.address')
        employee.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台员工添加
    def primaryKeyExist(self, employeeNo):  # 判断主键是否存在
        try:
            Employee.objects.get(employeeNo=employeeNo)
            return True
        except Employee.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Employee/employee_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        employeeNo = request.POST.get('employee.employeeNo') # 判断员工编号是否存在
        if self.primaryKeyExist(employeeNo):
            return JsonResponse({'success': False, 'message': '员工编号已经存在'})

        employee = Employee() # 新建一个员工对象然后获取参数
        employee.employeeNo = employeeNo
        employee.password = request.POST.get('employee.password')
        employee.name = request.POST.get('employee.name')
        employee.gender = request.POST.get('employee.gender')
        employee.inDate = request.POST.get('employee.inDate')
        try:
            employee.empPhoto = self.uploadImageFile(request,'employee.empPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        employee.telephone = request.POST.get('employee.telephone')
        employee.email = request.POST.get('employee.email')
        employee.address = request.POST.get('employee.address')
        employee.save() # 保存员工信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新员工
    def get(self, request, employeeNo):
        context = {'employeeNo': employeeNo}
        return render(request, 'Employee/employee_modify.html', context)

class BackSelfModifyView(BaseView):  # 后台更新员工
    def get(self, request):
        context = {'employeeNo':  request.session.get('username')}
        return render(request, 'Employee/employee_modify.html',context)


class ListView(BaseView):  # 后台员工列表
    def get(self, request):
        # 使用模板
        return render(request, 'Employee/employee_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        employeeNo = self.getStrParam(request, 'employeeNo')
        name = self.getStrParam(request, 'name')
        inDate = self.getStrParam(request, 'inDate')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        employees = Employee.objects.all()
        if employeeNo != '':
            employees = employees.filter(employeeNo__contains=employeeNo)
        if name != '':
            employees = employees.filter(name__contains=name)
        if inDate != '':
            employees = employees.filter(inDate__contains=inDate)
        if telephone != '':
            employees = employees.filter(telephone__contains=telephone)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(employees, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        employees_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        employeeList = []
        for employee in employees_page:
            employee = employee.getJsonObj()
            employeeList.append(employee)
        # 构造模板页面需要的参数
        employee_res = {
            'rows': employeeList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(employee_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除员工信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        employeeNos = self.getStrParam(request, 'employeeNos')
        employeeNos = employeeNos.split(',')
        count = 0
        try:
            for employeeNo in employeeNos:
                Employee.objects.get(employeeNo=employeeNo).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:

PythonProject/templates/Employee/employee_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>员工查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>员工查询</h1>
		</div>
		<form name="employeeQueryForm" id="employeeQueryForm" action="{% url 'Employee:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="employeeNo">员工编号:</label>
				<input type="text" id="employeeNo" name="employeeNo" value="{{ employeeNo }}" class="form-control" placeholder="请输入员工编号">
			</div>
			<div class="form-group">
				<label for="name">员工姓名:</label>
				<input type="text" id="name" name="name" value="{{ name }}" class="form-control" placeholder="请输入员工姓名">
			</div>
			<div class="form-group">
				<label for="inDate">入职日期:</label>
				<input type="text" id="inDate" name="inDate" class="form-control"  placeholder="请选择入职日期" value="{{ inDate }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
			<div class="form-group">
				<label for="telephone">联系电话:</label>
				<input type="text" id="telephone" name="telephone" value="{{ telephone }}" class="form-control" placeholder="请输入联系电话">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

	<div class="col-md-9 wow fadeInRight">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'Employee:frontList' %}">员工信息列表</a></li>
  			<li class="active">查询结果显示</li>
  			<a class="pull-right" href="{% url 'Employee:frontAdd' %}" style="display:none;">添加员工</a>
		</ul>
		<div class="row">
            {% for employee in employees_page %}
                {% if forloop.counter|add:-1|divisibleby:4 %}
			<div class="col-md-3 bottom15" style="clear: left;">
                {% else %}
            <div class="col-md-3 bottom15">
                {% endif %}
			  <a  href="{% url 'Employee:frontShow' employee.employeeNo %}"><img class="img-responsive" src="{{ employee.empPhoto.url }}" /></a>
			     <div class="showFields">
			     	<div class="field">
	            		员工编号:{{ employee.employeeNo }}
			     	</div>
			     	<div class="field">
	            		员工姓名:{{ employee.name }}
			     	</div>
			     	<div class="field">
	            		性别:{{ employee.gender }}
			     	</div>
			     	<div class="field">
	            		入职日期:{{ employee.inDate }}
			     	</div>
			     	<div class="field">
	            		联系电话:{{ employee.telephone }}
			     	</div>
			     	<div class="field">
	            		邮箱:{{ employee.email }}
			     	</div>
			        <a class="btn btn-primary top5" href="{% url 'Employee:frontShow' employee.employeeNo  %}">详情</a>
			        <a class="btn btn-primary top5" onclick="employeeEdit('{{ employee.employeeNo }}');" style="display: none;">修改</a>
			        <a class="btn btn-primary top5" onclick="employeeDelete('{{ employee.employeeNo }}');" style="display: none;">删除</a>
			     </div>
			</div>
			{% endfor %}

			<div class="row">
				<div class="col-md-12">
					<nav class="pull-left">
						<ul class="pagination">
							<li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }});" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
							{% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						</ul>
					</nav>
					<div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
				</div>
			</div>
		</div>
	</div>

  </div>
</div>
<div id="employeeEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;员工信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="employeeEditForm" id="employeeEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="employee_employeeNo_edit" class="col-md-3 text-right">员工编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="employee_employeeNo_edit" name="employee.employeeNo" class="form-control" placeholder="请输入员工编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="employee_password_edit" class="col-md-3 text-right">登录密码:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_password_edit" name="employee.password" class="form-control" placeholder="请输入登录密码">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_name_edit" class="col-md-3 text-right">员工姓名:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_name_edit" name="employee.name" class="form-control" placeholder="请输入员工姓名">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_gender_edit" class="col-md-3 text-right">性别:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_gender_edit" name="employee.gender" class="form-control" placeholder="请输入性别">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_inDate_edit" class="col-md-3 text-right">入职日期:</label>
		  	 <div class="col-md-9">
                <div class="input-group date employee_inDate_edit col-md-12" data-link-field="employee_inDate_edit" data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="employee_inDate_edit" name="employee.inDate" size="16" type="text" value="" placeholder="请选择入职日期" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_empPhoto_edit" class="col-md-3 text-right">员工照片:</label>
		  	 <div class="col-md-9">
			    <img  class="img-responsive" id="employee_empPhotoImg" border="0px"/><br/>
			    <input id="employee_empPhoto" name="employee.empPhoto" type="file" size="50" />
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_telephone_edit" class="col-md-3 text-right">联系电话:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_telephone_edit" name="employee.telephone" class="form-control" placeholder="请输入联系电话">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_email_edit" class="col-md-3 text-right">邮箱:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_email_edit" name="employee.email" class="form-control" placeholder="请输入邮箱">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="employee_address_edit" class="col-md-3 text-right">家庭地址:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="employee_address_edit" name="employee.address" class="form-control" placeholder="请输入家庭地址">
			 </div>
		  </div>
		</form> 
	    <style>#employeeEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxEmployeeModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.employeeQueryForm.currentPage.value = currentPage;
    document.employeeQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.employeeQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.employeeQueryForm.currentPage.value = pageValue;
    documentemployeeQueryForm.submit();
}

/*弹出修改员工界面并初始化数据*/
function employeeEdit(employeeNo) {
	$.ajax({
		url :  '/Employee/update/' + employeeNo,
		type : "get",
		dataType: "json",
		success : function (employee, response, status) {
			if (employee) {
				$("#employee_employeeNo_edit").val(employee.employeeNo);
				$("#employee_password_edit").val(employee.password);
				$("#employee_name_edit").val(employee.name);
				$("#employee_gender_edit").val(employee.gender);
				$("#employee_inDate_edit").val(employee.inDate);
				$("#employee_empPhotoImg").attr("src", employee.empPhoto);
				$("#employee_telephone_edit").val(employee.telephone);
				$("#employee_email_edit").val(employee.email);
				$("#employee_address_edit").val(employee.address);
				$('#employeeEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除员工信息*/
function employeeDelete(employeeNo) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Employee/deletes",
			data : {
				employeeNos : employeeNo,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#employeeQueryForm").submit();
					//location.href= basePath + "Employee/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交员工信息表单给服务器端修改*/
function ajaxEmployeeModify() {
	$.ajax({
		url :   '/Employee/update/' + $("#employee_employeeNo_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#employeeEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#employeeQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*入职日期组件*/
    $('.employee_inDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd',
    	minView: 2,
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
